### ISSUE TITLE
Implement "Last Changed Rev" instead of "Revision" field

### ISSUE THREAD

**Issue by moreaki** [mojohaus/buildnumber-maven-plugin#66]
It seems that the current notion of picking the revision information is the `Revision` field from the `svn info` information. However, I would need to have the `Last Changed Rev` information field. After searching the web and reading the documentation, I have not found a way to obtain this field. Is there a way, and if not, would it be possible to implement this (along the line of https://github.com/mojohaus/buildnumber-maven-plugin/pull/16/commits/8c0f41458e55e2fe3e3e9644437f7e1c832346e9)?

Example output from `svn info`:

``` yaml
Path: .
Working Copy Root Path: /<...>/dev/projects/proj-A
URL: http://example.com/svn/<...>/trunk
Relative URL: ^/<...>/trunk
Repository Root: http://example.com/svn/
Repository UUID: 8104d0a4-ed15-438a-b3ec-15d70441338f
Revision: 78855
Node Kind: directory
Schedule: normal
Last Changed Author: the.swede
Last Changed Rev: 78847
Last Changed Date: 2017-06-28 09:43:58 +0900 (Wed, 28 Jun 2017)
```

In the above excerpt one can spot that the overall company-wide svn revision counter field is at **78855**, while the individual project's svn counter for the last change is at **78847**. This is the one I would need.

Quite related is the following question on [StackOverflow](https://stackoverflow.com/questions/40438351/retrieve-svn-last-changed-revision-number-with-the-buildnumber-maven-plugin).
